import type { ScheduleConfig } from "../types/schedule";

export function createDefaultScheduleConfig(): ScheduleConfig {
  return {
    version: 1,
    updatedAt: new Date().toISOString(),
    business: {
      name: "Allied Remodeling",
      website: "https://alliedremodeling.com/",
      tagline: "Appointment scheduling for Allied Remodeling agents",
    },
    provider: {
      name: "Blazeo",
      website: "https://www.blazeo.com/",
      logoUrl: "https://www.blazeo.com/wp-content/uploads/2024/05/logo-blazeo.svg",
    },
    businessHours: {
      sunday: { open: "00:00", close: "00:00", closed: true },
      monday: { open: "08:00", close: "17:00" },
      tuesday: { open: "08:00", close: "17:00" },
      wednesday: { open: "08:00", close: "17:00" },
      thursday: { open: "08:00", close: "17:00" },
      friday: { open: "08:00", close: "17:00" },
      saturday: { open: "09:00", close: "13:00" },
    },
    defaultSlots: {
      sunday: [],
      monday: ["14:00", "18:00"],
      tuesday: ["10:00", "14:00", "18:00"],
      wednesday: ["10:00", "14:00", "18:00"],
      thursday: ["10:00", "14:00", "18:00"],
      friday: ["18:00"],
      saturday: [],
    },
    weeks: [
      {
        id: "week-2026-08-10",
        label: "Week of August 10th-16th",
        startDate: "2026-08-10",
        endDate: "2026-08-16",
        rules: [
          {
            id: "r1",
            label: "If Monday",
            days: ["monday"],
            timeCondition: "all",
            targetDate: "2026-08-11",
            slots: ["14:00", "18:00"],
          },
          {
            id: "r2",
            label: "If Tuesday",
            days: ["tuesday"],
            timeCondition: "all",
            targetDate: "2026-08-12",
          },
          {
            id: "r3",
            label: "If Wednesday",
            days: ["wednesday"],
            timeCondition: "all",
            targetDate: "2026-08-13",
          },
          {
            id: "r4",
            label: "If Thursday",
            days: ["thursday"],
            timeCondition: "all",
            targetDate: "2026-08-14",
          },
          {
            id: "r5",
            label: "If Friday before 5pm",
            days: ["friday"],
            timeCondition: "before",
            time: "17:00",
            targetDate: "2026-08-17",
          },
          {
            id: "r6",
            label: "If Friday after 5pm, Saturday, or Sunday",
            days: ["friday", "saturday", "sunday"],
            timeCondition: "after",
            time: "17:00",
            targetDate: "2026-08-18",
          },
        ],
      },
      {
        id: "week-2026-08-17",
        label: "Week of August 17th-22nd",
        startDate: "2026-08-17",
        endDate: "2026-08-22",
        rules: [
          {
            id: "r1",
            label: "If Monday",
            days: ["monday"],
            timeCondition: "all",
            targetDate: "2026-08-18",
          },
          {
            id: "r2",
            label: "If Tuesday",
            days: ["tuesday"],
            timeCondition: "all",
            targetDate: "2026-08-19",
          },
          {
            id: "r3",
            label: "If Wednesday",
            days: ["wednesday"],
            timeCondition: "all",
            targetDate: "2026-08-20",
          },
          {
            id: "r4",
            label: "If Thursday",
            days: ["thursday"],
            timeCondition: "all",
            targetDate: "2026-08-21",
          },
          {
            id: "r5",
            label: "If Friday before 5pm",
            days: ["friday"],
            timeCondition: "before",
            time: "17:00",
            targetDate: "2026-08-24",
          },
          {
            id: "r6",
            label: "If Friday after 5pm, Saturday, or Sunday",
            days: ["friday", "saturday", "sunday"],
            timeCondition: "after",
            time: "17:00",
            targetDate: "2026-08-25",
          },
        ],
      },
      {
        id: "week-2026-08-24",
        label: "Week of August 24th-29th",
        startDate: "2026-08-24",
        endDate: "2026-08-29",
        rules: [
          {
            id: "r1",
            label: "If Monday",
            days: ["monday"],
            timeCondition: "all",
            targetDate: "2026-08-25",
          },
          {
            id: "r2",
            label: "If Tuesday",
            days: ["tuesday"],
            timeCondition: "all",
            targetDate: "2026-08-26",
          },
          {
            id: "r3",
            label: "If Wednesday",
            days: ["wednesday"],
            timeCondition: "all",
            targetDate: "2026-08-27",
          },
          {
            id: "r4",
            label: "If Thursday",
            days: ["thursday"],
            timeCondition: "all",
            targetDate: "2026-08-28",
          },
          {
            id: "r5",
            label: "If Friday before 5pm",
            days: ["friday"],
            timeCondition: "before",
            time: "17:00",
            targetDate: "2026-08-31",
          },
          {
            id: "r6",
            label: "If Friday after 5pm, Saturday, or Sunday",
            days: ["friday", "saturday", "sunday"],
            timeCondition: "after",
            time: "17:00",
            targetDate: "2026-09-01",
          },
        ],
      },
    ],
  };
}
